# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [12]:
import numpy as np

# Create a 1D array with 12 elements
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("1D array:")
print(array_1d)
# Reshape the 1D array into a 2D array with dimensions (3, 4)
array_2d = array_1d.reshape(3, 4)

print("Reshaped 2D array:")
print(array_2d)
print()

# Create two 1D arrays
array_1 = np.array([13, 14, 15, 16])
array_2 = np.array([17, 18, 19, 20])

# Concatenate the arrays horizontally
concatenated_horizontal = np.hstack((array_1, array_2))

# Concatenate the arrays vertically
concatenated_vertical = np.vstack((array_1, array_2))

print("Concatenated horizontally:")
print(concatenated_horizontal)
print()

print("Concatenated vertically:")
print(concatenated_vertical)


1D array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped 2D array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Concatenated horizontally:
[13 14 15 16 17 18 19 20]

Concatenated vertically:
[[13 14 15 16]
 [17 18 19 20]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [14]:
def classify_emails(emails):
    important_keywords = ["urgent", "important", "action required"]
    promotions_keywords = ["deal", "discount", "offer"]
    spam_keywords = ["lottery", "prize", "free", "click here"]

    important_emails = []
    promotions_emails = []
    spam_emails = []

    for email in emails:
        # Convert email content to lowercase for case-insensitive matching
        lower_email = email.lower()

        # Check for important keywords
        if any(keyword in lower_email for keyword in important_keywords):
            important_emails.append(email)
        # Check for promotions keywords
        elif any(keyword in lower_email for keyword in promotions_keywords):
            promotions_emails.append(email)
        # Check for spam keywords or patterns
        elif any(keyword in lower_email for keyword in spam_keywords):
            spam_emails.append(email)

    return important_emails, promotions_emails, spam_emails

# Example usage:
emails_to_classify = [
    "Urgent: Action required on your account",
    "Special promotion: Get 20% off on our products",
    "Congratulations! You've won a prize!",
    "Check out our latest deals and discounts",
    "Important notice regarding your subscription",
    "Click here for a free trial"
]

important, promotions, spam = classify_emails(emails_to_classify)

# Print the classified emails
print("Important Emails:")
print(important)
print("\nPromotions Emails:")
print(promotions)
print("\nSpam Emails:")
print(spam)


Important Emails:
['Urgent: Action required on your account', 'Important notice regarding your subscription']

Promotions Emails:
['Check out our latest deals and discounts']

Spam Emails:
["Congratulations! You've won a prize!", 'Click here for a free trial']


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [15]:
# Create an English-Spanish dictionary
english_spanish_dict = {
    "hello": "hola",
    "goodbye": "adiós",
    "thank you": "gracias",
    "yes": "sí",
    "no": "no",
    # Add more words as needed
}

# Function to look up English words and print their Spanish translations
def lookup_translation():
    while True:
        # Ask the user to input an English word
        word_to_translate = input("Enter an English word (type 'exit' to end): ").lower()

        # Check if the user wants to exit
        if word_to_translate == 'exit':
            print("Exiting the dictionary. Goodbye!")
            break

        # Check if the word exists in the dictionary
        if word_to_translate in english_spanish_dict:
            # Print the Spanish translation
            translation = english_spanish_dict[word_to_translate]
            print(f"The Spanish translation of '{word_to_translate}' is: {translation}")
        else:
            # Inform the user that the translation is not available
            print(f"Translation not available for '{word_to_translate}'.")

# Call the function to start the translation lookup loop
lookup_translation()


Enter an English word (type 'exit' to end): yes
The Spanish translation of 'yes' is: sí
Enter an English word (type 'exit' to end): goodbye
The Spanish translation of 'goodbye' is: adiós
Enter an English word (type 'exit' to end): exit
Exiting the dictionary. Goodbye!


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

**Some** tree example

In [30]:
import pandas as pd
dataset_url = 'https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv'
df = pd.read_csv(dataset_url)
print("First few rows of the DataFrame:")
print(df.head())


First few rows of the DataFrame:
   Rank                      Name Platform    Year         Genre Publisher  \
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo   
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37  


In [20]:
 #1. Calculate the total global sales for all games
total_global_sales = df['Global_Sales'].sum()
print(f"Total Global Sales: {total_global_sales} million units")

Total Global Sales: 8920.44 million units


In [31]:
# 2. Find the game with the highest global sales
highest_global_sales_game = df.loc[df['Global_Sales'].idxmax()]['Name']
print(f"Game with the highest global sales: {highest_global_sales_game}")

Game with the highest global sales: Wii Sports


In [32]:
# 3. Determine the average sales for each region
average_sales_per_region = df[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean()
print("Average Sales for Each Region:")
print(average_sales_per_region)

Average Sales for Each Region:
NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64


In [33]:
# 4. Find the top 5 most popular game genres based on global sales
top_genres_global_sales = df.groupby('Genre')['Global_Sales'].sum().nlargest(5)
print("Top 5 Game Genres Based on Global Sales:")
print(top_genres_global_sales)

Top 5 Game Genres Based on Global Sales:
Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64


In [34]:
# 5. Calculate the total sales for each genre in each region
total_sales_per_genre_per_region = df.groupby(['Genre', 'Platform'])[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()
most_popular_genre_na_sales = total_sales_per_genre_per_region['NA_Sales'].idxmax()
print(f"Most Popular Genre in North America (NA_Sales): {most_popular_genre_na_sales}")

Most Popular Genre in North America (NA_Sales): ('Shooter', 'X360')


In [35]:
# 6. Display last 10 rows
last_10_rows = df.tail(10)
print("Last 10 Rows:")
print(last_10_rows)

Last 10 Rows:
        Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
1

In [36]:
# 7. Determine the top 3 gaming platforms with the highest global sales
top_3_platforms_global_sales = df.groupby('Platform')['Global_Sales'].sum().nlargest(3)
print("Top 3 Gaming Platforms with the Highest Global Sales:")
print(top_3_platforms_global_sales)


Top 3 Gaming Platforms with the Highest Global Sales:
Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


In [37]:
# 8. Calculate the market share for each genre
market_share_per_genre = (df.groupby('Genre')['Global_Sales'].sum() / total_global_sales) * 100
print("Market Share (Percentage of Global Sales) for Each Genre:")
print(market_share_per_genre)

Market Share (Percentage of Global Sales) for Each Genre:
Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64


In [38]:

# 9. Calculate the correlation coefficient between NA_Sales and EU_Sales
correlation_coefficient = df['NA_Sales'].corr(df['EU_Sales'])
print(f"Correlation Coefficient between NA_Sales and EU_Sales: {correlation_coefficient}")

Correlation Coefficient between NA_Sales and EU_Sales: 0.7677267483702631
